fix: AddDependency with onlyIfUsing: "*" cause: StringIndexOutOfBoundsException (#6057)
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.StringLatin1.charAt (StringLatin1.java:48)
    at java.lang.String.charAt (String.java:1517)
    at org.openrewrite.java.search.UsesType.<init> (UsesType.java:58)
    at org.openrewrite.gradle.AddDependency$1.usesType (AddDependency.java:165)
    at org.openrewrite.gradle.AddDependency$1.lambda$visit$0 (AddDependency.java:177)
    at java.util.HashMap.compute (HashMap.java:1316)
    at org.openrewrite.gradle.AddDependency$1.lambda$visit$3 (AddDependency.java:177)
    at java.util.Optional.ifPresent (Optional.java:178)
    at org.openrewrite.gradle.AddDependency$1.visit (AddDependency.java:176)
    at org.openrewrite.gradle.AddDependency$1.visit (AddDependency.java:155)
    at org.openrewrite.java.dependencies.AddDependency$1.visit (AddDependency.java:152)
    at org.openrewrite.java.dependencies.AddDependency$1.visit (AddDependency.java:149)
```