bug: Handle NoClassDefFoundError when loading YAML recipes with missing recipe dependencies (#4186)
* bug: Handle NoClassDefFoundError when loading YAML recipes with missing class dependencies

* add unit tests

* Applied IntelliJ auto-formatter

* Add no option recipes that throw NoClassDefFoundError to list of invalid recipes