Fix `NoSuchMethodError` during Java 11 parsing when the LST generation is running on an older Java 11 version which doesn't have `JCTree.JCVariableDecl.declaredUsingVar()`: Instead of calling `com.sun.tools.javac.tree.JCTree.JCVariableDecl.declaredUsingVar()` (which was added in 2022, around 11.0.15) figure out manually whether the lambda parameter was declared with the `var` keyword or not