Fix: synchronize lazy initialization of contributers of `DeclarativeRecipe`
fixes:

```
java.util.concurrent.ExecutionException: org.openrewrite.internal.RecipeRunException: java.util.ConcurrentModificationException
  java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
  java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
Caused by org.openrewrite.internal.RecipeRunException: java.util.ConcurrentModificationException
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:292)
  org.openrewrite.TreeVisitor.visitNonNull(TreeVisitor.java:164)
Caused by java.util.ConcurrentModificationException: null
  java.base/java.util.ArrayList.sort(ArrayList.java:1723)
  org.openrewrite.config.DeclarativeRecipe.getContributors(DeclarativeRecipe.java:371)
  org.openrewrite.config.DeclarativeRecipe.getContributors(DeclarativeRecipe.java:363)
  org.openrewrite.config.DeclarativeRecipe.getContributors(DeclarativeRecipe.java:363)
  org.openrewrite.config.DeclarativeRecipe.getContributors(DeclarativeRecipe.java:363)
  org.openrewrite.config.DeclarativeRecipe.getContributors(DeclarativeRecipe.java:363)
  org.openrewrite.config.DeclarativeRecipe.getContributors(DeclarativeRecipe.java:363)
  org.openrewrite.config.DeclarativeRecipe.getContributors(DeclarativeRecipe.java:363)
  ...
```