Revert changes made to add method wrapping style (#6121)
* Revert "Fix NPE and NoSuchMethodError (#6120)"

This reverts commit bc68beb837148aac65fcdc3ac0356fb4b1da527d.

* Revert "Added method wrapping style (#6106)"

This reverts commit 485cffca369f526152b9ace62cc42385d90698f0.