Fix NPE
getMethodType() is nullable and must be checked at every invocation.

java.lang.NullPointerException: Cannot invoke
"org.openrewrite.java.tree.JavaType$Method.hasFlags(org.openrewrite.java.tree.Flag[])"
because the return value of
"org.openrewrite.java.tree.J$MethodInvocation.getMethodType()" is null
at org.openrewrite.java.search.SemanticallyEqual$SemanticallyEqualVisitor.visitMethodInvocation
(SemanticallyEqual.java:874)