Do not except after to be non null in handleError
Actual error is being swallowed in case of a failure during generate:

```
java.lang.NullPointerException: after is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:235)
	at org.openrewrite.scheduling.RecipeRunCycle.handleError(RecipeRunCycle.java:295)
	at org.openrewrite.scheduling.RecipeRunCycle.lambda$generateSources$6(RecipeRunCycle.java:159)
	at org.openrewrite.scheduling.RecipeStack.reduce(RecipeStack.java:60)
	at org.openrewrite.scheduling.RecipeRunCycle.generateSources(RecipeRunCycle.java:127)
	```