Prevent NPE on null Space of unknown origin (#3436)
Seen in CLI
```
Running recipe in github.com/Netflix/conductor@main
org.openrewrite.internal.RecipeRunException: java.lang.NullPointerException: Cannot invoke "org.openrewrite.java.tree.Space.getComments()" because "space" is null
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:329)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:184)
	at org.openrewrite.RecipeScheduler$RecipeRunCycle.lambda$editSources$3(RecipeScheduler.java:231)
	at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:147)
	at org.openrewrite.table.RecipeRunStats.recordEdit(RecipeRunStats.java:56)
	at org.openrewrite.RecipeScheduler$RecipeRunCycle.lambda$editSources$4(RecipeScheduler.java:228)
	at org.openrewrite.RecipeScheduler$RecipeRunCycle.lambda$mapForRecipeRecursively$5(RecipeScheduler.java:330)
	at io.moderne.serialization.ModerneLargeSourceSet.edit(Unknown Source)
	at io.moderne.serialization.ModerneLargeSourceSet.edit(Unknown Source)
	at org.openrewrite.RecipeScheduler$RecipeRunCycle.mapForRecipeRecursively(RecipeScheduler.java:323)
	at org.openrewrite.RecipeScheduler$RecipeRunCycle.editSources(RecipeScheduler.java:201)
	at org.openrewrite.RecipeScheduler.scheduleRun(RecipeScheduler.java:76)
	at org.openrewrite.Recipe.run(Recipe.java:279)
	at org.openrewrite.Recipe.run(Recipe.java:275)
	at org.openrewrite.Recipe.run(Recipe.java:271)
	at io.moderne.modjava.commands.run.Run.call(Run.java:151)
	at io.moderne.modjava.commands.run.Run.call(Run.java:38)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.moderne.modjava.ModJava.main(ModJava.java:28)
Caused by: java.lang.NullPointerException: Cannot invoke "org.openrewrite.java.tree.Space.getComments()" because "space" is null
	at org.openrewrite.java.JavaVisitor.visitSpace(JavaVisitor.java:155)
	at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1293)
	at org.openrewrite.java.JavaVisitor.visitCompilationUnit(JavaVisitor.java:463)
	at org.openrewrite.java.tree.J$CompilationUnit.acceptJava(J.java:1520)
	at org.openrewrite.java.tree.J.accept(J.java:59)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:278)
	... 25 more
Error:  java.lang.NullPointerException: Cannot invoke "org.openrewrite.java.tree.Space.getComments()" because "space" is null
org.openrewrite.internal.RecipeRunException: java.lang.NullPointerException: Cannot invoke "org.openrewrite.java.tree.Space.getComments()" because "space" is null
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:329)
	at io.moderne.serialization.ModerneLargeSourceSet.a(Unknown Source)
	at io.moderne.serialization.ModerneLargeSourceSet.edit(Unknown Source)
	at io.moderne.serialization.ModerneLargeSourceSet.edit(Unknown Source)
	at org.openrewrite.RecipeScheduler$RecipeRunCycle.mapForRecipeRecursively(RecipeScheduler.java:323)
	at org.openrewrite.RecipeScheduler$RecipeRunCycle.editSources(RecipeScheduler.java:201)
	at org.openrewrite.RecipeScheduler.scheduleRun(RecipeScheduler.java:76)
	at org.openrewrite.Recipe.run(Recipe.java:279)
	at org.openrewrite.Recipe.run(Recipe.java:275)
	at org.openrewrite.Recipe.run(Recipe.java:271)
	at io.moderne.modjava.commands.run.Run.call(Run.java:151)
	at io.moderne.modjava.commands.run.Run.call(Run.java:38)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.moderne.modjava.ModJava.main(ModJava.java:28)
Caused by: java.lang.NullPointerException: Cannot invoke "org.openrewrite.java.tree.Space.getComments()" because "space" is null
	at org.openrewrite.java.JavaVisitor.visitSpace(JavaVisitor.java:155)
	at org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1293)
	at org.openrewrite.java.JavaVisitor.visitCompilationUnit(JavaVisitor.java:463)
	at org.openrewrite.java.tree.J$CompilationUnit.acceptJava(J.java:1520)
	at org.openrewrite.java.tree.J.accept(J.java:59)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:278)
	... 20 more
```